# Generated by Django 2.1.3 on 2018-11-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biological', '0002_auto_20181016_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paineffect',
            name='level',
        ),
        migrations.RemoveField(
            model_name='paineffect',
            name='location',
        ),
        migrations.AlterField(
            model_name='paineffect',
            name='painType',
            field=models.CharField(choices=[('P', 'Pain'), ('I', 'Infections'), ('O', 'Other')], max_length=8),
        ),
    ]
