# Generated by Django 2.1.3 on 2018-11-06 17:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biological', '0005_auto_20181106_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paineffect',
            name='level',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='paineffect',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biological.BodyPart'),
        ),
    ]
