# Generated by Django 2.1.2 on 2018-11-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mutations',
            new_name='Mutation',
        ),
    ]
