# Generated by Django 2.1.3 on 2018-11-06 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_auto_20181102_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changes',
            old_name='globalEndDate',
            new_name='EndDate',
        ),
        migrations.RenameField(
            model_name='changes',
            old_name='globalStartDate',
            new_name='StartDate',
        ),
        migrations.RenameField(
            model_name='changes',
            old_name='bodyPart',
            new_name='location',
        ),
        migrations.AddField(
            model_name='changes',
            name='level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
