# Generated by Django 2.1.3 on 2018-11-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_mutation_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='sideEffects',
            field=models.ManyToManyField(null=True, to='biological.PainEffect'),
        ),
    ]
