# Generated by Django 2.1.2 on 2018-10-15 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biological', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalStartDate', models.DateTimeField(auto_now_add=True)),
                ('globalEndDate', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('bodyPart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biological.BodyPart')),
                ('pain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biological.PainEffect')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('manufacture', models.CharField(max_length=40)),
                ('sideEffects', models.ManyToManyField(to='biological.PainEffect')),
            ],
        ),
        migrations.CreateModel(
            name='Mutations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Seizure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalStartDate', models.DateTimeField(auto_now_add=True)),
                ('globalEndDate', models.DateTimeField(auto_now=True)),
                ('globalNote', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
