# Generated by Django 2.1.3 on 2018-11-06 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20181106_1616'),
        ('medical', '0003_auto_20181106_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='changes',
            name='medications',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.MedicationUse'),
        ),
        migrations.AddField(
            model_name='changes',
            name='seizure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.Seizure'),
        ),
    ]
