# Generated by Django 2.1.3 on 2018-11-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_auto_20181106_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changes',
            name='level',
        ),
        migrations.RemoveField(
            model_name='changes',
            name='location',
        ),
        migrations.AlterField(
            model_name='medication',
            name='sideEffects',
            field=models.ManyToManyField(to='biological.PainEffect'),
        ),
    ]
