# Generated by Django 2.1.3 on 2018-11-06 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biological', '0008_auto_20181106_1720'),
        ('person', '0009_auto_20181107_0008'),
        ('medical', '0007_auto_20181106_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('medications', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.MedicationUse')),
                ('pain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biological.PainEffect')),
                ('seizure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.Seizure')),
            ],
        ),
        migrations.RemoveField(
            model_name='changes',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='changes',
            name='pain',
        ),
        migrations.RemoveField(
            model_name='changes',
            name='seizure',
        ),
        migrations.DeleteModel(
            name='Changes',
        ),
    ]
