# Generated by Django 2.1.2 on 2018-11-02 15:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
        ('facilities', '0001_initial'),
        ('person', '0002_auto_20181016_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='MdeicationUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Medication')),
                ('place_taken', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('isActive', models.BooleanField(default=True)),
                ('startDate', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, 2))),
                ('endDate', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, 1))),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Medication')),
            ],
        ),
        migrations.RemoveField(
            model_name='perscripton',
            name='medicationId',
        ),
        migrations.RemoveField(
            model_name='perscripton',
            name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diagnosisDate',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Perscripton',
        ),
        migrations.AddField(
            model_name='prescription',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Profile'),
        ),
        migrations.AddField(
            model_name='mdeicationuse',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Profile'),
        ),
    ]
