# Generated by Django 2.1.3 on 2018-11-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20181102_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diagnosisDate',
            field=models.IntegerField(),
        ),
    ]
