# Generated by Django 2.1.3 on 2018-11-06 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('person', '0005_auto_20181106_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.DateTimeField(null=True)),
                ('amount', models.IntegerField()),
                ('place_taken', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.Facility')),
            ],
        ),
        migrations.RemoveField(
            model_name='mdeicationuse',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='mdeicationuse',
            name='place_taken',
        ),
        migrations.RemoveField(
            model_name='mdeicationuse',
            name='profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='birthday',
            new_name='birthdayYear',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='diagnosisDate',
            new_name='diagnosisYear',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medication',
        ),
        migrations.DeleteModel(
            name='MdeicationUse',
        ),
        migrations.AddField(
            model_name='medicationuse',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Profile'),
        ),
    ]
