# Generated by Django 2.1.3 on 2018-11-06 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20181106_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='endDate',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 2, 0, 1)),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='startDate',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 2, 0, 2)),
        ),
    ]
