# Generated by Django 2.1.2 on 2018-10-16 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perscripton',
            name='endDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='perscripton',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perscripton',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, 1)),
        ),
        migrations.AddField(
            model_name='profile',
            name='hmo',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
