# Generated by Django 2.1.3 on 2018-11-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20181106_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='originID',
        ),
        migrations.AddField(
            model_name='profile',
            name='originID_fatherOfFather',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='originID_fatherOfMother',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='originID_motherOfFather',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='originID_motherOfMother',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
