# Generated by Django 2.1.3 on 2018-11-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biological', '0007_auto_20181106_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paineffect',
            name='painCharacterization',
            field=models.CharField(blank=True, choices=[('D', 'Dull'), ('S', 'Sharp'), ('B', 'Burning'), ('P', 'Pulling')], max_length=8),
        ),
        migrations.AlterField(
            model_name='paineffect',
            name='painType',
            field=models.CharField(blank=True, choices=[('P', 'Pain'), ('I', 'Infections'), ('D', 'Diarrhea'), ('N', 'Nausea'), ('V', 'Vomiting'), ('C', 'Consipation'), ('O', 'Other')], max_length=8),
        ),
    ]
